### ISSUE TITLE
Format of functions and doctrings

### ISSUE THREAD

**Issue by ccurtis7** [Aidan-Jackson/CHEME_599_Amphiphiliphile-#3]
Great job on your first set of functions! A few things to spruce up:

* Make sure that you don't use single line comments e.g. 

`# This is a comment`

Instead, use the docstring comment block by using three sets of quotes e.g.

`"""This will make one big comment instead of an individual line. """`

* Make sure that all functions have the structure:

```
def first_function(input1, input2):

     return outputs
```

I believe one function wasn't technically a function, but rather a block of code not embedded in a function structure.

You also do not need to specify `short summary` or `long summary` within the docstring, as that is implied.

**Comment by leveillec** [comment]
We will do this in future
