### ISSUE TITLE
Consolidate functions into modules.

### ISSUE THREAD

**Issue by ccurtis7** [Aidan-Jackson/CHEME_599_Amphiphiliphile-#4]
Your first functions are in separate files, which is fine, as you are all developing code on your own branches.

But you should also come up with a structure to organize your intended functions. So functions that fall under the same umbrella of use cases are in the same `.py` file (also make sure your functions are in `.py` files and not raw text files). For instance, remember how `skimage` has a `morphology` module, a `filter` module, a `util` module, etc? See if you can develop a similar structure, then make a `.py` file for each set of functions you intend to create.

**Comment by fuzzylgc** [comment]
This has been addressed. I made the directory with the original code into a 'raw_code' directory. I made a new directory called 'amph' to serve as the package. This package directory includes the modules 'blob_detection_method.py' and 'other_method.py' as well as a 'test.py' for testing purposes. The 'test.py' is not imported in the initialization file. Both modules are composed of a single class of the same name as the module to prepare for classes later one. I have also added a notebook called 'package_use.ipynb' which illustrates how to use the new package. The 'blob_detection' module is composed of functions which use the premade blob detection package. The 'other_methods' module is for functions using other methods of finding blobs. These functions are the five functions which were written by the group members and were previously individual files. There is currently an issue that functions can not be imported individually. This may be a problem with the class structure or a circular dependency which is being opened in new issue to be addressed later. Please see the 'amph' directory if you want to further investigate the structure of the package.

**Comment by fuzzylgc** [comment]
This issue has been closed, please see above.
