### ISSUE TITLE
Data in repo?

### ISSUE THREAD

**Issue by ccurtis7** [Aidan-Jackson/CHEME_599_Amphiphiliphile-#5]
You have included some image datasets in your repository. That's usually not good practice, but maybe you're ok with it for now. If you're repo is public, there are issues with sharing data you may want to keep private. And there is a limit to how much data you can put in your repo. If you add any more, you may evenutally run up against that limit. Consider moving your data to a shared platform accessible to all your teammates.

**Comment by ccurtis7** [comment]
Another note, if you add data to a Github repo, it will always be hard to completely remove. Even if you delete these files, they will live in your commit history. That means I could re-wind to a previous version and find them. Completely deleting them will be difficult, but it is possible.

**Comment by hweakly** [comment]
As we would like to eventually store and upload more data, we created a Google colab to hold all the data.
