### ISSUE TITLE
A code file

### ISSUE THREAD

**Issue by ccurtis7** [Aidan-Jackson/CHEME_599_Amphiphiliphile-#6]
Usually, `.py` files are stored in a sub-folder with the same name or a similar name to the repo name. I would recommend something like `amphiphiliphile`.

**Comment by Aidan-Jackson** [comment]
Closing Statement:
I have created a folder on the master branch where each member's functions will be stored named "amphiphiliphile". I then copied each member's .py files into the folder as new files. These .py files have not been edited to include solutions to other issues posted.
