### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by ccurtis7** [Aidan-Jackson/CHEME_599_Amphiphiliphile-#7]
In addition to your short desription of your project on your README, can you include a list of use cases? Use cases are the problems your code is seeking to address, or the situations in which your software package could be used. For instance, the use cases of an ATM could be to check your balance or to withdraw cash.

**Comment by zackcohen55** [comment]
Ok here are some use cases.  I will also post to the README file!

Use cases:Our current set of functions are designed to detect bright circles from a dark background.  In our case, we use these functions for the following purposes:1) to detect regions of aqueous dye encapsulated by a membrane.  2) by first inverting the image intensity values, we hope to use these functions to detect oil droplets (dye-free regions) from a dye-free background.
More generally, this code could be used to:1) detect dyed emulsions from a dye-free background2) detect stars in the night sky
